version: '3.6'

services:

  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"



  puppeteer:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
    - "3000"
